apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverese-string-deployment
  labels:
    app: reverese-string
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reverese-string
  template:
    metadata:
      labels:
        app: reverese-string
    spec:
      containers:
      - name: reverese-string
        image: lipsa2020/task:string-app-docker
        ports:
        - containerPort: 5000
